[package]
name = "todo-ci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
grep = "0.2.8"
ignore = "0.4.18"
regex = "1.6.0"
termcolor = "1.1.3"
time = { version = "0.3.11", features = ["parsing", "serde"] }
walkdir = "2.3.2"
